<?php
include_once('Articulo.php');
/**
  * Implements hook_menu().
  */
function mymodule_menu() {
  $items = array();
  $items['ws/json'] = array(
    'title' => 'JSON',
    'description' => 'JSON web service',
    'page callback' => 'ws_json',
    'access callback' => TRUE,
    'type'=> MENU_CALLBACK,
  );
  return $items;
}

function ws_json(){
 	$article=new Articulo();
   if (empty($_POST['idNode']) && empty($_POST['comment']))
  	{
    $article->getImages();
	}	 

 
   if (!empty($_POST['idNode']) && empty($_POST['comment'])) {
	$nodoId=(int)$_POST['idNode'];
	$article->retrieveAllContent($nodoId);
	//echo 'Hola mundo';
  }
  if (!empty($_POST['idNode']) && !empty($_POST['comment'])){
	
	 $article->postComment($_POST['idNode'],$_POST['comment']);
	}
}
