<?php
/**
  * Implements hook_menu().
  */
function mymodule_menu() {
  $items = array();
  $items['ws/json'] = array(
    'title' => 'JSON',
    'description' => 'JSON web service',
    'page callback' => 'ws_json',
    'access callback' => 1
  );
  return $items;
}


function ws_json(){
  $response = array();
  if (!empty($_POST["index"]) && empty($_POST["idNode"]) && empty($_POST["comentario"])) {
    retrieveAll();
  }

}


function retrieveAll(){
    $elementos=array();
    for ($j=2;$j<11;$j++){
      $node= node_load($j);
      $arregloFinal=array('ID Nodo'=> $nodo->nid , 'Titulo'=>$nodo->title);
      $elementos[''.$j]=$arregloFinal;

    }

$arr=array("Posts"=>$elementos);
echo drupal_json_output($arr);
drupal_exit();

  }
?>
